"""Install mg CLI pointing to a source worktree for development."""

import os
import stat
from pathlib import Path

from mg import cmd
from mg.errors import CommandError


def define() -> cmd.Def:
    """Define the dev install command."""
    return cmd.Def(
        description="Install mg CLI pointing to a source worktree",
        flags=[
            cmd.Flag("branch"),
            cmd.Flag("force", type=bool),
        ],
    )


def execute(ctx: cmd.Ctx) -> None:
    """Execute the dev install command."""
    branch = ctx.args.get_one("branch", default_value="main")
    force = ctx.args.has("force")

    mg_root = ctx.paths.root
    worktree_path = mg_root / "worktrees" / branch

    # Verify worktree exists
    if not worktree_path.exists():
        available = _list_worktrees(mg_root)
        raise CommandError(
            f"Worktree not found: {worktree_path}\n\n"
            f"Available worktrees: {', '.join(available) or '(none)'}"
        )

    # Verify mg-cli exists in worktree
    mg_cli_path = worktree_path / "mg-cli"
    if not mg_cli_path.exists():
        raise CommandError(
            f"mg-cli not found in worktree: {mg_cli_path}\n\n"
            "This worktree doesn't appear to contain the mg source code."
        )

    # Check if mg already installed
    install_path = Path.home() / ".local" / "bin" / "mg"
    if install_path.exists() and not force:
        raise CommandError(
            f"mg already installed at {install_path}\n\n"
            "Use --force to overwrite."
        )

    # Create ~/.local/bin if needed
    install_path.parent.mkdir(parents=True, exist_ok=True)

    # Write shell script
    script = _generate_script(mg_root, branch)
    install_path.write_text(script)

    # Make executable
    install_path.chmod(install_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    ctx.print(f"Installed mg at {install_path}")
    ctx.print(f"Source: {worktree_path}/mg-cli")
    ctx.print()
    ctx.print("Make sure ~/.local/bin is in your PATH.")


def _list_worktrees(mg_root: Path) -> list[str]:
    """List available worktrees."""
    worktrees_dir = mg_root / "worktrees"
    if not worktrees_dir.exists():
        return []
    return [d.name for d in worktrees_dir.iterdir() if d.is_dir()]


def _generate_script(mg_root: Path, branch: str) -> str:
    """Generate the mg shell script."""
    return f'''#!/bin/bash
# Generated by mg dev install
# Source: {mg_root}/worktrees/{branch}
exec uv run --project "{mg_root}/worktrees/{branch}/mg-cli" mg "$@"
'''
