"""Install mg CLI and tools pointing to a source worktree for development."""

import stat
from pathlib import Path

from mg import cmd
from mg.errors import CommandError

# Tools to install: (script_name, package_dir, entry_point)
_TOOLS = [
    ("mg", "mg-cli", "from mg_cli import main; main()"),
    ("mg-tui", "mg-tui", "from mg_tui import main; main()"),
]


def define() -> cmd.Def:
    """Define the dev install command."""
    return cmd.Def(
        description="Install mg CLI and tools pointing to a source worktree",
        flags=[
            cmd.Flag("branch"),
            cmd.Flag("force", type=bool),
        ],
    )


def execute(ctx: cmd.Ctx) -> None:
    """Execute the dev install command."""
    branch = ctx.args.get_one("branch", default_value="main")
    force = ctx.args.has("force")

    mg_root = ctx.paths.root
    worktree_path = mg_root / "worktrees" / branch

    # Verify worktree exists
    if not worktree_path.exists():
        available = _list_worktrees(mg_root)
        raise CommandError(
            f"Worktree not found: {worktree_path}\n\n"
            f"Available worktrees: {', '.join(available) or '(none)'}"
        )

    bin_dir = Path.home() / ".local" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)

    for script_name, package_dir, entry_point in _TOOLS:
        # Verify package exists in worktree
        package_path = worktree_path / package_dir
        if not package_path.exists():
            raise CommandError(
                f"{package_dir} not found in worktree: {package_path}\n\n"
                "This worktree doesn't appear to contain the mg source code."
            )

        install_path = bin_dir / script_name
        if install_path.exists() and not force:
            raise CommandError(
                f"{script_name} already installed at {install_path}\n\n"
                "Use --force to overwrite."
            )

        script = _generate_script(mg_root, branch, package_dir, entry_point)
        install_path.write_text(script)
        install_path.chmod(
            install_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
        )

        ctx.print(f"Installed {script_name} at {install_path}")
        ctx.print(f"  Source: {package_path}")

    ctx.print()
    ctx.print("Make sure ~/.local/bin is in your PATH.")


def _list_worktrees(mg_root: Path) -> list[str]:
    """List available worktrees."""
    worktrees_dir = mg_root / "worktrees"
    if not worktrees_dir.exists():
        return []
    return [d.name for d in worktrees_dir.iterdir() if d.is_dir()]


def _generate_script(
    mg_root: Path, branch: str, package_dir: str, entry_point: str
) -> str:
    """Generate a shell script that runs a tool via uv from the worktree."""
    # MG_PROG passes the script name so mg-cli displays it correctly
    # (needed because we invoke via python -c, which loses argv[0]).
    return f'''#!/bin/bash
# Generated by mg dev install
# Source: {mg_root}/worktrees/{branch}/{package_dir}
export MG_PROG="$(basename "$0")"
exec uv run --project "{mg_root}/worktrees/{branch}/{package_dir}" python -c "{entry_point}" "$@"
'''
