"""Install haiv CLI and tools pointing to a source worktree for development."""

import stat
import sys
from pathlib import Path

from haiv import cmd
from haiv.errors import CommandError

# Tools to install: (script_name, package_dir, entry_point)
_TOOLS = [
    ("hv", "haiv-cli", "from haiv_cli import main; main()"),
    ("hv-tui", "haiv-tui", "from haiv_tui import main; main()"),
]


def define() -> cmd.Def:
    """Define the dev install command."""
    return cmd.Def(
        description="Install haiv CLI and tools pointing to a source worktree",
        flags=[
            cmd.Flag("branch"),
            cmd.Flag("force", type=bool),
        ],
    )


def execute(ctx: cmd.Ctx) -> None:
    """Execute the dev install command."""
    branch = ctx.args.get_one("branch", default_value="main")
    force = ctx.args.has("force")

    haiv_root = ctx.paths.root
    worktree_path = haiv_root / "worktrees" / branch

    # Verify worktree exists
    if not worktree_path.exists():
        available = _list_worktrees(haiv_root)
        raise CommandError(
            f"Worktree not found: {worktree_path}\n\n"
            f"Available worktrees: {', '.join(available) or '(none)'}"
        )

    bin_dir = Path.home() / ".local" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)

    is_windows = sys.platform == "win32"

    for script_name, package_dir, entry_point in _TOOLS:
        # Verify package exists in worktree
        package_path = worktree_path / package_dir
        if not package_path.exists():
            raise CommandError(
                f"{package_dir} not found in worktree: {package_path}\n\n"
                "This worktree doesn't appear to contain the haiv source code."
            )

        # Build list of (path, content) pairs to install.
        # On Windows we install both a .cmd (for cmd/powershell) and an
        # extensionless bash script (for git-bash / WSL / Claude Code).
        targets: list[tuple[Path, str]] = []
        if is_windows:
            targets.append((
                bin_dir / f"{script_name}.cmd",
                _generate_cmd_script(haiv_root, branch, package_dir, entry_point),
            ))
            targets.append((
                bin_dir / script_name,
                _generate_script(haiv_root, branch, package_dir, entry_point),
            ))
        else:
            targets.append((
                bin_dir / script_name,
                _generate_script(haiv_root, branch, package_dir, entry_point),
            ))

        for install_path, script in targets:
            if install_path.exists() and not force:
                raise CommandError(
                    f"{script_name} already installed at {install_path}\n\n"
                    "Use --force to overwrite."
                )

        for install_path, script in targets:
            install_path.write_text(script, encoding="utf-8")
            if not install_path.suffix:
                # Mark extensionless scripts as executable (matters for
                # git-bash and WSL; no-op on pure Windows filesystems).
                install_path.chmod(
                    install_path.stat().st_mode
                    | stat.S_IXUSR
                    | stat.S_IXGRP
                    | stat.S_IXOTH
                )
            ctx.print(f"Installed {install_path.name} at {install_path}")

        ctx.print(f"  Source: {package_path}")

    ctx.print()
    ctx.print(f"Make sure {bin_dir} is in your PATH.")


def _list_worktrees(haiv_root: Path) -> list[str]:
    """List available worktrees."""
    worktrees_dir = haiv_root / "worktrees"
    if not worktrees_dir.exists():
        return []
    return [d.name for d in worktrees_dir.iterdir() if d.is_dir()]


def _generate_script(
    haiv_root: Path, branch: str, package_dir: str, entry_point: str
) -> str:
    """Generate a bash script that runs a tool via uv from the worktree."""
    # HV_PROG passes the script name so haiv-cli displays it correctly
    # (needed because we invoke via python -c, which loses argv[0]).
    return f'''#!/bin/bash
# Generated by hv dev install
# Source: {haiv_root}/worktrees/{branch}/{package_dir}
export HV_PROG="$(basename "$0")"
unset VIRTUAL_ENV
exec uv run --project "{haiv_root}/worktrees/{branch}/{package_dir}" python -c "{entry_point}" "$@"
'''


def _generate_cmd_script(
    haiv_root: Path, branch: str, package_dir: str, entry_point: str
) -> str:
    """Generate a Windows cmd script that runs a tool via uv from the worktree."""
    project = haiv_root / "worktrees" / branch / package_dir
    return f'''@echo off
REM Generated by hv dev install
REM Source: {project}
set HV_PROG=%~n0
set VIRTUAL_ENV=
uv run --project "{project}" python -c "{entry_point}" %*
'''
